theme: jekyll-theme-minimal
title: Castle Mock - Mock REST APIs and SOAP web-services
description: Castle Mock is a web application that provides the functionality to mock out RESTful APIs and SOAP web services. This functionality allows client-side developers to completely mimic a server side behaviour and shape the responses themselves.
logo: assets/img/logo.png
show_downloads: false